# Generated by Django 6.0.2 on 2026-04-05 02:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_fecha_nacimiento_usuario_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=150)),
                ('nombre_negocio', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('domicilio', models.CharField(max_length=255)),
                ('documento_identidad', models.FileField(upload_to='proveedores/documentos/identidad/')),
                ('certificado_productos', models.FileField(blank=True, null=True, upload_to='proveedores/documentos/certificados/')),
                ('registro_marca', models.FileField(blank=True, null=True, upload_to='proveedores/documentos/marcas/')),
                ('listado_productos', models.TextField(blank=True)),
                ('origen_productos', models.TextField(blank=True)),
                ('aprobada', models.BooleanField(default=False)),
                ('rechazada', models.BooleanField(default=False)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Solicitud de Proveedor',
                'verbose_name_plural': 'Solicitudes de Proveedores',
            },
        ),
        migrations.AlterField(
            model_name='usuario',
            name='user_type',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('proveedor', 'Proveedor')], default='cliente', max_length=20, verbose_name='Tipo de Usuario'),
        ),
        migrations.CreateModel(
            name='ProviderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_negocio', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='proveedores/perfiles/')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('en_revision', 'En Revisión')], default='en_revision', max_length=20)),
                ('email_contacto', models.EmailField(blank=True, max_length=254)),
                ('telefono_contacto', models.CharField(blank=True, max_length=20)),
                ('domicilio_negocio', models.CharField(blank=True, max_length=255)),
                ('whatsapp', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('color_fondo', models.CharField(default='#ffffff', max_length=7)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_proveedor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Proveedor',
                'verbose_name_plural': 'Perfiles de Proveedores',
            },
        ),
    ]
