# Generated by Django 6.0.2 on 2026-04-07 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_providerapplication_alter_usuario_user_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='nombre_publico',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='telegram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='tiktok',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='providerprofile',
            name='estado',
            field=models.CharField(choices=[('activa', 'Activa'), ('en espera', 'En espera'), ('en_revision', 'En Revisión')], default='en_revision', max_length=20),
        ),
    ]
