# Generated by Django 6.0.2 on 2026-04-10 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_providerprofile_nombre_publico_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='fecha_nacimiento',
        ),
        migrations.AddField(
            model_name='usuario',
            name='es_mayor_edad',
            field=models.BooleanField(default=False, verbose_name='Es mayor de 18'),
        ),
    ]
