# Generated by Django 6.0.2 on 2026-04-11 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0002_factura_pagada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemfactura',
            name='cantidad',
            field=models.PositiveIntegerField(),
        ),
    ]
