# Generated by Django 6.0.2 on 2026-03-26 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0001_initial'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcarrito',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto'),
        ),
    ]
