# Generated by Django 6.0.2 on 2026-03-25 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.CharField(blank=True, default='default.png.png', max_length=200, null=True),
        ),
    ]
