# Generated by Django 6.0.2 on 2026-03-25 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.CharField(blank=True, default='defaul.png', max_length=200, null=True),
        ),
    ]
