# Generated by Django 6.0.2 on 2026-04-09 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_alter_producto_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='proveedores/imagenes/'),
        ),
    ]
