# Generated by Django 6.0.2 on 2026-04-09 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_alter_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='proveedores/imagenes/'),
        ),
    ]
