# Generated by Django 6.0.2 on 2026-04-11 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0009_producto_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
    ]
